name: auto

on:
  schedule:
    - cron: 0 0/10 * * *
  workflow_dispatch:  # 允许手动运行

jobs:
  auto_login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and browser
        run: npx playwright install --with-deps chromium

      - name: Run lognin script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          NETLIB_ACCOUNTS: ${{ secrets.NETLIB_ACCOUNTS }}
          DNSHE_ACCOUNTS: ${{ secrets.DNSHE_ACCOUNTS }}
        run: npm start
